### ISSUE TITLE
How to make it work in Knulli

### ISSUE THREAD

**Issue by casanovaalonso** [retro-m-dev/ROMDownloader-Anbernic-StockOS#1]
To make it work with Knulli:

- Go to anbernic.py change the sd1 folder to **"/userdata/roms"**
- Modify the map to
```
self.__rom_folder_mapping = {
            "PSP": "psp",
            "PS": "psx",
            "GBA": "gba",
            "GBC": "gbc",
            "GB": "gb",
            "NDS": "nds",
            "N64": "n64",
        }
```
- Place the ROMDownloader folder + ROMDownloader.sh under the **/userdata/roms/ports folder**
- Execute the .sh file from the ports menu

I didn't test the code with a second SD; this is my first day using Knulli, to be honest. I tested it with an Anbernic RG40XX-V

**Comment by kittyk4y** [comment]
This gets the app to show up on a stock RG353V, but will not launch. (Adding this here since I followed these instructions to get it on the 353V)

**Comment by casanovaalonso** [comment]
2 options:
- Python version
- The paths are different in your machine, maybe you are using sd2? I didn't check with a second sd
-

**Comment by kittyk4y** [comment]
- Not sure of the Python version and I’m not sure where to check. 
- I used SSH to access internal memory (or maybe SD1? I’m not sure but it’s the same path)

**Comment by retro-m-dev** [comment]
It would be interesting to make versions compatible with other devices.

@casanovaalonso can you confirm that your changes work on Knulli?

@kittyk4y to check your Python version, connect to your device via SSH and run the command:
python3 --version

**Comment by casanovaalonso** [comment]
It works for me in Knulli. The problem is related to the paths. Python tries to create a file in a non-existing folder, and it breaks. Once that is fixed, you will be able to download the games in knulli.

**Comment by retro-m-dev** [comment]
What about the different path between SD1 and SD2?
In Stock OS, you have two directories for the SDs, is it the same for Knulli?
I would like to create a version compabile with Knulli thanks to your suggestions, but I don't have the SO. Would you like to test it?

**Comment by casanovaalonso** [comment]
I think you indeed have two directories, but yesterday was my first day using the OS, so I'm not sure.

**Comment by kittyk4y** [comment]
Python version on the 353V is 3.9.2.

**Comment by retro-m-dev** [comment]
@kittyk4y so I guess a porting for 353V is feasible with little effort. I could work on it but I don't have the device, I would need your help for testing. Tell me if you are interested

**Comment by kittyk4y** [comment]
Definitely would be interested in helping out!

**Comment by retro-m-dev** [comment]
@kittyk4y great, I'll contact you!

@casanovaalonso thanks for your contribution, I created a new branch named knulli with your suggestions. I haven't tested it because I haven't knulli but I hope someone will do it. For now, I close this issue
